; ============================================================
; WxReadAssistant Windows Installer Script (Inno Setup 6)
;
; Invoked by scripts/build_release.py:
;   iscc /DAppVersion=2.2.5 /DDistDir=<staged full dir> /DOutputDir=<release dir> installer\wxread_assistant.iss
;
; Output: WxReadAssistant-v<version>-setup.exe
;   - Self-contained installer (all PyInstaller deps included)
;   - Default install dir: {autopf}\WxReadAssistant
;   - User data in %APPDATA%\WxReadAssistant is NEVER touched
;     by install or uninstall.
; ============================================================

#define MyAppName "WxReadAssistant"
#define MyAppExeName "WxReadAssistant.exe"

[Setup]
; Stable AppId: reuse the same GUID across versions so upgrades work in place.
AppId={{7F3A2B9C-1D4E-4A8B-B5C6-2E9F1A3D4B5E}
AppName={#MyAppName}
AppVersion={#AppVersion}
AppVerName={#MyAppName} v{#AppVersion}
AppPublisher={#MyAppName}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
; Allow per-user install (LocalAppData) when the user is not admin.
PrivilegesRequiredOverridesAllowed=dialog
; The app is built with 64-bit Python (PySide6 has no 32-bit wheels).
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
OutputDir={#OutputDir}
OutputBaseFilename=WxReadAssistant-v{#AppVersion}-setup
; App icon shared with the EXE resource (generated by scripts/make_icon.py).
; Relative paths resolve against the .iss directory (SourcePath).
SetupIconFile=..\assets\app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
CloseApplications=yes
RestartApplications=no

[Languages]
; SourcePath = the directory containing this .iss (trailing backslash).
; Fallback order: bundled .isl -> compiler's own .isl -> English.
#define CsIsl SourcePath + "Languages\ChineseSimplified.isl"
#if FileExists(CsIsl)
Name: "chinesesimplified"; MessagesFile: {#CsIsl}
#elif FileExists(CompilerPath + "\Languages\ChineseSimplified.isl")
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
#else
Name: "english"; MessagesFile: "compiler:Default.isl"
#endif

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; Mirror the whole PyInstaller onedir output into {app}.
Source: "{#DistDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Nothing here on purpose: user data in %APPDATA%\WxReadAssistant must survive uninstall.
